### ISSUE TITLE
[Bug] Runs extremely slow

### ISSUE THREAD

**Issue by hXtreme** [rmon-vfer/notYandereSimCode#1]
idk, I'm getting abysmal frame rates while running this.

_(joke issue)_

**Comment by Redd56** [comment]
(_joke_ remark_)

**Comment by TerWebz** [comment]
have you tried turning off then on again?
__(joke)__

**Comment by hXtreme** [comment]
@TerWebz That did it, I deleted all the code now it works so fast that my frame rate counter can't keep up with its speed.

Thanks!

_(Joke resolution)_
