### ISSUE TITLE
Cannot modify the return value of because it is not a variable & other errors

### ISSUE THREAD

**Issue by PekkuTheSan** [rmon-vfer/notYandereSimCode#3]
I can't get it to work without errors. Anyone else has the same problem?
![image](https://user-images.githubusercontent.com/68597857/88057766-d2ace080-cb62-11ea-82a2-493729a7018f.png)

**Comment by rmon-vfer** [comment]
The code it's not a complete Unity Project so it won't run.
Also, it is nonsense trying to run it on VS.
